version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: rhombus
    binary: rhombus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: rhombus
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: rhombus
    package_name: rhombus
    vendor: Rhombus Systems
    homepage: "https://github.com/RhombusSystems/rhombus-cli"
    description: "CLI for the Rhombus API"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

brews:
  - repository:
      owner: RhombusSystems
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    name: rhombus
    homepage: "https://github.com/RhombusSystems/rhombus-cli"
    description: "CLI for the Rhombus API"
    license: "MIT"
    install: |
      bin.install "rhombus"
    test: |
      system "#{bin}/rhombus", "--help"
