package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

func WriteGeneratedFiles(services []Service, outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}

	// Write register.go
	if err := writeRegister(services, outDir); err != nil {
		return err
	}

	// Write per-service files
	for _, svc := range services {
		if err := writeService(svc, outDir); err != nil {
			return fmt.Errorf("writing %s: %w", svc.FileName, err)
		}
	}

	return nil
}

func writeRegister(services []Service, outDir string) error {
	tmpl, err := template.New("register").Parse(registerTemplate)
	if err != nil {
		return fmt.Errorf("parsing register template: %w", err)
	}

	path := filepath.Join(outDir, "register.go")
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating register.go: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, services); err != nil {
		return fmt.Errorf("executing register template: %w", err)
	}

	return gofmt(path)
}

func writeService(svc Service, outDir string) error {
	funcMap := template.FuncMap{
		"paramMeta": func(params []Param) string {
			return formatParamMeta(params)
		},
	}

	tmpl, err := template.New("service").Funcs(funcMap).Parse(serviceTemplate)
	if err != nil {
		return fmt.Errorf("parsing service template: %w", err)
	}

	path := filepath.Join(outDir, svc.FileName)
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating %s: %w", svc.FileName, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, svc); err != nil {
		return fmt.Errorf("executing service template for %s: %w", svc.ServiceName, err)
	}

	return gofmt(path)
}

func formatParamMeta(params []Param) string {
	if len(params) == 0 {
		return "nil"
	}
	s := "[]params.ParamMeta{\n"
	for _, p := range params {
		example := "nil"
		if p.Example != nil {
			switch v := p.Example.(type) {
			case string:
				example = fmt.Sprintf("%q", v)
			case float64:
				if v == float64(int64(v)) {
					example = fmt.Sprintf("int64(%d)", int64(v))
				} else {
					example = fmt.Sprintf("float64(%v)", v)
				}
			case bool:
				example = fmt.Sprintf("%v", v)
			default:
				// For complex types (arrays, objects), skip the example
				_ = v
				example = "nil"
			}
		}
		s += fmt.Sprintf("\t\t\t\t{Name: %q, FlagName: %q, Type: %q, Required: %v, Example: %s},\n",
			p.Name, p.FlagName, p.Type, p.Required, example)
	}
	s += "\t\t\t}"
	return s
}

func gofmt(path string) error {
	cmd := exec.Command("gofmt", "-w", path)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gofmt %s: %s\n%s", path, err, string(out))
	}
	return nil
}

var registerTemplate = `// Code generated by rhombus-cli codegen. DO NOT EDIT.
package generated

import "github.com/spf13/cobra"

func RegisterAll(root *cobra.Command) {
{{- range .}}
	root.AddCommand(New{{.FuncName}}Cmd())
{{- end}}
}
`

var serviceTemplate = `// Code generated by rhombus-cli codegen. DO NOT EDIT.
package generated

import (
	"github.com/spf13/cobra"
	"github.com/RhombusSystems/rhombus-cli/internal/client"
	"github.com/RhombusSystems/rhombus-cli/internal/config"
	"github.com/RhombusSystems/rhombus-cli/internal/output"
	"github.com/RhombusSystems/rhombus-cli/internal/params"
)

func New{{.FuncName}}Cmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{.ServiceName}}",
		Short: "{{.Tag}} operations",
	}
{{range .Operations}}
	cmd.AddCommand(new{{.GoFuncName}}Cmd())
{{- end}}
	return cmd
}
{{range .Operations}}
func new{{.GoFuncName}}Cmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{.CommandName}}",
		Short: "{{.Summary}}",
		Long:  "{{.Description}}",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg := config.LoadFromCmd(cmd)
			flags := params.CollectFlags(cmd)
			cliJSON, _ := cmd.Flags().GetString("cli-input-json")
			skeleton, _ := cmd.Flags().GetBool("generate-cli-skeleton")
			if skeleton {
				return params.PrintSkeleton({{paramMeta .Params}})
			}
			body, err := params.BuildBody(flags, cliJSON)
			if err != nil {
				return err
			}
			result, err := client.APICall(cfg, "{{.Path}}", body)
			if err != nil {
				return err
			}
			return output.FormatOutput(cmd, result)
		},
	}
{{range .Params}}	cmd.Flags().String("{{.FlagName}}", "", "{{.Description}}")
{{end}}	cmd.Flags().String("cli-input-json", "", "JSON input (inline or file://path)")
	cmd.Flags().Bool("generate-cli-skeleton", false, "Print input skeleton and exit")
	return cmd
}
{{end}}`
