package client

import (
	"bytes"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io"
	"net/http"
	"os"
	"sync"

	"github.com/RhombusSystems/rhombus-cli/internal/config"
)

var (
	httpClients   = make(map[string]*http.Client)
	httpClientsMu sync.Mutex
)

func APICall(cfg config.Config, path string, body map[string]any) (map[string]any, error) {
	if cfg.ApiKey == "" {
		return nil, fmt.Errorf("no API key configured. Run 'rhombus login' or 'rhombus configure'")
	}

	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request body: %w", err)
	}

	url := cfg.EndpointURL + path
	req, err := http.NewRequest("POST", url, bytes.NewReader(jsonBody))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")
	req.Header.Set("x-auth-apikey", cfg.ApiKey)

	// Set partner org header if specified
	if cfg.PartnerOrg != "" {
		req.Header.Set("x-auth-org", cfg.PartnerOrg)
	}

	var client *http.Client

	if cfg.AuthType == config.AuthTypeCert && cfg.CertFile != "" && cfg.KeyFile != "" {
		// mTLS cert-based auth
		if cfg.IsPartner {
			req.Header.Set("x-auth-scheme", "partner-api")
		} else {
			req.Header.Set("x-auth-scheme", "api")
		}
		client, err = getCertClient(cfg.CertFile, cfg.KeyFile)
		if err != nil {
			return nil, fmt.Errorf("loading client certificate: %w", err)
		}
	} else {
		// Token-based auth
		if cfg.IsPartner {
			req.Header.Set("x-auth-scheme", "partner-api-token")
		} else {
			req.Header.Set("x-auth-scheme", "api-token")
		}
		client = http.DefaultClient
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("API error (HTTP %d): %s", resp.StatusCode, string(respBody))
	}

	var result map[string]any
	if len(respBody) > 0 {
		if err := json.Unmarshal(respBody, &result); err != nil {
			return nil, fmt.Errorf("failed to parse response JSON: %w", err)
		}
	}

	return result, nil
}

// getCertClient returns a cached HTTP client configured with the given client certificate.
// Uses raw PEM loading to handle certificates with negative serial numbers
// (generated by the Rhombus CA using Java's BigInteger from random UUIDs).
func getCertClient(certFile, keyFile string) (*http.Client, error) {
	cacheKey := certFile + "|" + keyFile

	httpClientsMu.Lock()
	defer httpClientsMu.Unlock()

	if c, ok := httpClients[cacheKey]; ok {
		return c, nil
	}

	certPEM, err := os.ReadFile(certFile)
	if err != nil {
		return nil, fmt.Errorf("reading cert file: %w", err)
	}
	keyPEM, err := os.ReadFile(keyFile)
	if err != nil {
		return nil, fmt.Errorf("reading key file: %w", err)
	}

	// Parse the PEM blocks directly without x509 serial number validation
	certBlock, _ := pem.Decode(certPEM)
	if certBlock == nil {
		return nil, fmt.Errorf("failed to decode certificate PEM")
	}
	keyBlock, _ := pem.Decode(keyPEM)
	if keyBlock == nil {
		return nil, fmt.Errorf("failed to decode key PEM")
	}

	cert := tls.Certificate{
		Certificate: [][]byte{certBlock.Bytes},
	}

	cert.PrivateKey, err = parsePrivateKey(keyBlock.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parsing private key: %w", err)
	}

	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{cert},
	}

	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: tlsConfig,
		},
	}

	httpClients[cacheKey] = client
	return client, nil
}

func parsePrivateKey(der []byte) (any, error) {
	if key, err := x509.ParseECPrivateKey(der); err == nil {
		return key, nil
	}
	if key, err := x509.ParsePKCS8PrivateKey(der); err == nil {
		return key, nil
	}
	if key, err := x509.ParsePKCS1PrivateKey(der); err == nil {
		return key, nil
	}
	return nil, fmt.Errorf("unsupported private key type")
}
